Old caching folder /content/datasets/librispeech_asr/clean/2.1.0/2712a8f82f0d20807a56faadcd08734f9bdd24c850bb118ba21ff33ebff0432f for dataset librispeech_asr exists but no data were found. Removing it.
WARNING:datasets.builder:Old caching folder /content/datasets/librispeech_asr/clean/2.1.0/2712a8f82f0d20807a56faadcd08734f9bdd24c850bb118ba21ff33ebff0432f for dataset librispeech_asr exists but no data were found. Removing it.
Downloading data: 100%|█████████████████████████████████████████████████████| 23.0G/23.0G [10:31<00:00, 36.5MB/s]
Downloading data files: 100%|█████████████████████████████████████████████████████| 4/4 [10:33<00:00, 158.28s/it]
Extracting data files: 100%|███████████████████████████████████████████████████████| 4/4 [04:23<00:00, 65.85s/it]
Generatin
Generating train.360 split: 100%|████████████████████████████████| 104014/104014 [04:42<00:00, 368.63 examples/s]
Generatin
Generatin
Traceback (most recent call last):
  File "/content/Speech_Audio_Recognition/whisper_fine_tune.py", line 63, in <module>
    raw_dataset = load_dataset(
                  ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/datasets/load.py", line 2149, in load_dataset
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/datasets/builder.py", line 1173, in as_dataset
    raise NotImplementedError(f"Loading a dataset cached in a {type(self._fs).__name__} is not supported.")
NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported.
